# Generated by Django 5.0 on 2023-12-05 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_id_post_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='avatar',
            field=models.ImageField(blank=True, default='static/assets/img/person-2.jpg', null=True, upload_to=''),
        ),
    ]
